@echo off
echo Starting Enhanced Trading Optimization Web App...
echo ===================================================
echo 🚀 Initializing server...
echo 📊 Loading enhanced simulation engine...
echo 🔧 Date format fixes applied...
echo 🌐 Server will start at http://localhost:5000
echo ===================================================
".\venv_new\Scripts\python.exe" web_app.py
pause
